// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5cWClxQU6XfAx-o645E-FOFYZQPLplA',
    appId: '1:101677701207:web:2d4c01fb1d222728ca2b12',
    messagingSenderId: '101677701207',
    projectId: 'al-mihrab-f98c7',
    authDomain: 'al-mihrab-f98c7.firebaseapp.com',
    storageBucket: 'al-mihrab-f98c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByeNBl_SD8ap3vLd9-QtF29EveGTFXZAc',
    appId: '1:101677701207:android:d33dcc4e84eb7eebca2b12',
    messagingSenderId: '101677701207',
    projectId: 'al-mihrab-f98c7',
    storageBucket: 'al-mihrab-f98c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOn3P6rZAJOd8eoZDk7lYykjLRtHlh5go',
    appId: '1:101677701207:ios:3d9e67720a681279ca2b12',
    messagingSenderId: '101677701207',
    projectId: 'al-mihrab-f98c7',
    storageBucket: 'al-mihrab-f98c7.firebasestorage.app',
    iosBundleId: 'com.mihrab.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOn3P6rZAJOd8eoZDk7lYykjLRtHlh5go',
    appId: '1:101677701207:ios:3d9e67720a681279ca2b12',
    messagingSenderId: '101677701207',
    projectId: 'al-mihrab-f98c7',
    storageBucket: 'al-mihrab-f98c7.firebasestorage.app',
    iosBundleId: 'com.mihrab.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz5cWClxQU6XfAx-o645E-FOFYZQPLplA',
    appId: '1:101677701207:web:0930c77de17f87d6ca2b12',
    messagingSenderId: '101677701207',
    projectId: 'al-mihrab-f98c7',
    authDomain: 'al-mihrab-f98c7.firebaseapp.com',
    storageBucket: 'al-mihrab-f98c7.firebasestorage.app',
  );

}